# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rob Cleozier Blog
description: > # this means to ignore newlines until "baseurl:"
  My personal blog. Just random photos and some programming related posts
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://robbinscleozier.com" # the base hostname & protocol for your site
twitter_username: robsmanifesto
github_username:  rcleozier

# Build settings
markdown: kramdown
highlighter: Pygments
